# Generated by Django 3.0.6 on 2020-06-06 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('sid', models.CharField(max_length=3)),
                ('mobile', models.CharField(max_length=10)),
                ('roles', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student_register.Roles')),
            ],
        ),
    ]
